### ISSUE TITLE
Add EU Counties To Sale Page

### ISSUE THREAD

**Issue by cshrem** [vanbexlabs/mainstreet-salev2#14]
Add these countries to either the passport/ID card fields.

**Comment by cshrem** [comment]
I will look through the portal when Michael emails and give the list: 

Turkey, Switzerland, Sweden, Spain, Portugal, Norway, Netherlands, Luxembourg, Italy, Ireland, Germany, France, Denmark, Belgium, Austria.

**Comment by lisacheng** [comment]
Hey @Tulun 

Austria - Passport
Belgium - Passport
Denmark - National ID type: NationalID
France - National ID type: NationalID
Germany - Passport
Ireland - National ID type: SocialService
Italy - National ID type: SocialService
Luxembourg: Passport
Netherlands: NationalID type: NationalID
Norway: Passport
Portugal: Passport
Spain: National ID type: NationalID
Sweden: National ID type: NationalID
Switzerland: Passport
Turkey: National ID type: National ID

**for passport countries, we are only verifying by address

**Comment by lisacheng** [comment]
done
