### ISSUE TITLE
Message to investors

### ISSUE THREAD

**Issue by cshrem** [vanbexlabs/mainstreet-salev2#3]
Next to the Passport section we should say

 "If you are having an issue with verification or general questions, please join our Slack Live Chat - https://intellisysfund.slack.com/ or email hello@intellisys.ai"

Should also be on ALL the error message pages and on the top of the sale page.

**Comment by lisacheng** [comment]
added to the top of the page

**Comment by lisacheng** [comment]
Jason also added this to the error message
