### ISSUE TITLE
Blocktrades iFrame should default to MIT

### ISSUE THREAD

**Issue by cshrem** [vanbexlabs/mainstreet-salev2#4]
for eth->mit: https://blocktrades.us/session/6a056871-8b14-4368-a481-101a32439f39/trade/eth/mit_ito

for btc--> mit 

for eth->mit: https://blocktrades.us/session/6a056871-8b14-4368-a481-101a32439f39/trade/btc/mit_ito

I think we should have it defult to MIT, thoughts?

**Comment by lisacheng** [comment]
already done by Jason Kiraly, site is currently sending: 
"<iframe src=https://blocktrades.us/sessions/" + blocktradesBody.body.token + "/btc/mit_ito></iframe>"
