### ISSUE TITLE
*Important* Sale page token information

### ISSUE THREAD

**Issue by cshrem** [vanbexlabs/mainstreet-salev2#5]
On the sale page on the top: 

1 ETH = 12 MIT

Week 1-2 (10%)
1 ETH = 13.3 MIT
Weeks 3-5 (5%)
1 ETH = 12.6

Bulk Bonuses (You can stack weekly and bulk bonuses)

$500,000 - 2M USD 
1 ETH = 12.45 MIT (3.75%)
$2M +
1 ETH = 12.9 MIT (7.5%)

**Comment by lisacheng** [comment]
added here https://github.com/vanbexlabs/mainstreet-salev2/commit/baa4c599385dfb22bcfdee09dd614b978bc5b817
