### ISSUE TITLE
List of Blocktrades Currencies

### ISSUE THREAD

**Issue by lisacheng** [vanbexlabs/mainstreet-salev2#6]
We can add a list of currencies accepted in the sale (via Blocktrades) if we are given a list

**Comment by cshrem** [comment]
Yes, thats a good idea Ill ask Dan

**Comment by cshrem** [comment]
Bitcoin, BitShares, Dash, Dogecoin, Ethereum, Litecoin, Muse, NuBits, NuShares, Steem

**Comment by lisacheng** [comment]
done
